@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsShmIsRemoteReady
start
:struct IPCS_SHM_GLOBAL_TYPE *remote_global; sint32 err = -IPC_SHM_E_INVAL;
:ipcsHwFlushCacheRemote(instance);;
if (ipcsInstanceIsFree(instance) == IPC_SHM_INSTANCE_USED?) then (yes)
  :remote_global = (struct IPCS_SHM_GLOBAL_TYPE *)ipcsOsGetRemoteShm(instance);;
  if (remote_global->state != IPC_SHM_STATE_READY?) then (yes)
    :err = -IPC_SHM_E_NOT_READY;
  else (no)
    :err = IPC_SHM_E_OK;
  endif
else (no)
endif
:return err;
stop
@enduml
