@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsShmAcquireBuf
start
:uintptr_t buf_addr = NULL;
:ipcsHwFlushCacheLocal(instance); ipcsHwFlushCacheRemote(instance);
if (ipcsInstanceIsFree(instance) == IPC_SHM_INSTANCE_USED?) then (yes)
  :chan = getManagedChan(instance, chan_id);
  if ((chan == NULL) || (mem_size == 0u) || (ipcsCheckMchanIntegrity(chan) != OK)?) then (yes)
    :buf_addr = NULL;
  else (no)
    :pool_id = 0;;
    while (pool_id < chan->num_pools?)
      :pool = &chan->pools[pool_id];;
      if (mem_size > pool->buf_size?) then (yes)
        :pool_id++;;
      else (no)
        :err = ipcsQueuePop(&pool->bd_queue, &bd);;
        if (err == IPC_SHM_E_OK?) then (yes)
          break
        else (no)
          :pool_id++;;
        endif
      endif
    endwhile
    if (pool_id == chan->num_pools?) then (yes)
      :buf_addr = NULL;
    else (no)
      :buf_addr = pool->local_pool_addr + bd.buf_id * pool->buf_size;
    endif
  endif
else (no)
endif
:return (void *)buf_addr;
stop
@enduml
