@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsHwIrqNotify
start
if (mscm_tx_irq != IPC_IRQ_NONE?) then (yes)
  :read remote_core / msi_tx_index from priv;;
  :set IPC_MSCM_IRCPnIRx[..].IPC_IGR |= INT_EN;;
endif
stop
@enduml
