@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsHwFlushCache static
start
if (IPC_D_CACHE_ENABLE defined?) then (yes)
  :MCAL_DATA_SYNC_BARRIER(); MCAL_INSTRUCTION_SYNC_BARRIER();;
  repeat
    :S32_SCB->DCCIMVAC = data_addr_tmp;;
    :data_addr_tmp += IPC_DCACHE_LINE_SIZE;;
    :data_size_tmp -= IPC_DCACHE_LINE_SIZE;;
  repeat while (data_size_tmp > 0?) is (yes)
  :MCAL_DATA_SYNC_BARRIER(); MCAL_INSTRUCTION_SYNC_BARRIER();;
else (no)
endif
stop
@enduml
