@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsShmHardirqInstance autosar
start
if ((id[instance].state != IPC_SHM_INSTANCE_DISABLED) && (id[instance].rx_irq_num != IPC_IRQ_NONE)?) then (yes)
  :os_status = DisableInterruptSource(id[instance].isr_id_handler);;
  if (id[instance].msg_received == MSG_NOT_RECEIVED?) then (yes)
    :id[instance].msg_received = MSG_IS_RECEIVED;;
  endif
  :os_status = SetEvent(ipcsShmSoftirq, IPC_EVENT_RX_IRQ);;
else (no)
endif
stop
@enduml
