@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsHwIrqEnable
start
if (mscm_rx_irq != IPC_IRQ_NONE?) then (yes)
  note right
    unless USING_OS_AUTOSAROS compile flag set IRSPRC enable bit
  end note
  :IP_MSCM->IRSPRC[ipc_hw_priv[instance].mscm_rx_irq] |= ((uint16)1u << (ipc_hw_priv[instance].local_core - (uint8)IPC_M7_0 + 1u));;
else (no)
endif
stop
@enduml
