@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsShmHardirqInstance FreeRTOS
start
:higher_prio_task_woken = pdFALSE;;
:task_critical_status_from_isr = taskENTER_CRITICAL_FROM_ISR();;
if (id[instance].state != DISABLED?) then (yes)
  :ipcsHwIrqDisable(instance);;
  :ipcsHwIrqClear(instance);;
  if (msg_received == MSG_NOT_RECEIVED?) then (yes)
    :msg_received = MSG_IS_RECEIVED;;
  endif
  :vTaskNotifyGiveFromISR(softirq_handle, &higher_prio_task_woken);;
endif
:taskEXIT_CRITICAL_FROM_ISR(task_critical_status_from_isr);;
:portYIELD_FROM_ISR(higher_prio_task_woken);;
stop
@enduml
