@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title unmanagedChannelInit
start
:chan from priv UM; sint32 err = -IPC_SHM_E_INVAL;
if (cfg->size <= IPC_SHM_MAX_UMNG_SIZE?) then (yes)
  :save size rx_cb cb_arg;;
  :link local_mem/remote_mem pointers;;
  :local sentinel = IPC_UCHAN_SENTINEL; local tx_count = 0; remote_tx_copy = 0;;
  :err = IPC_SHM_E_OK;
else (no)
endif
:return err;
stop
@enduml
