@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsHwFlushCacheLocal
start
        if (IPC_D_CACHE_ENABLE defined?) then (yes)
          :data_addr = ipcsOsGetLocalShm(instance)
data_size = ipc_hw_priv[instance].shm_size
tmp_size = data_size + (data_addr & (IPC_DCACHE_LINE_SIZE - 1U))
tmp_addr = data_addr;;
          :ipcsHwFlushCache(tmp_addr,tmp_size);;
        else (no)
          :(void)instance;
        endif
        stop
@enduml
