@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
title ipcsShmInitChannels
start
        :local_shm = ipcsOsGetLocalShm(instance)
remote_shm = ipcsOsGetRemoteShm(instance)
global = (struct IPCS_SHM_GLOBAL_TYPE *)local_shm;;
        :local_chan = local_shm + sizeof(struct IPCS_SHM_GLOBAL_TYPE)
remote_chan = remote_shm + sizeof(struct IPCS_SHM_GLOBAL_TYPE)
err = -IPC_SHM_E_INVAL;;
        :i = 0;
        while (i < ipc_shm_priv_data[instance].num_channels?)
          :err = ipcsShmInitChannel(instance,i,local_chan,remote_chan,&cfg->channels[i]);;
          if (err == IPC_SHM_E_OK?) then (yes)
            :chan_size = getChanMemmapSize(instance, i)
local_chan += chan_size
remote_chan += chan_size;;
            :i++;;
          else (no)
            :ipcsOsFree(instance); ipcsHwFree(instance);;
            break
          endif
        endwhile
        :return err;
        stop
@enduml
