@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
:priv.id[instance].state = IPC_SHM_INSTANCE_DISABLED;
:ipcsHwIrqDisable(instance);
:munmap(remote_shm_map, remote_shm_offset + shm_size)\nmunmap(local_shm_map, local_shm_offset + shm_size);
:i = 0;
while (i < IPC_SHM_MAX_INSTANCES?) is (yes)
  if (priv.id[i].state == IPC_SHM_INSTANCE_ENABLED?) then (yes)
    :return;
stop
  endif
  :i++;
endwhile (no)
if (priv.ipc_files_opened == IPC_STATUS_SET?) then (yes)
  :pthread_cancel(priv.irq_thread_id)\npthread_join(priv.irq_thread_id, &res)\npriv.ipc_soft_created = IPC_STATUS_CLEAR;
  :close(priv.ipc_usr_fd)\nclose(priv.dev_mem_fd);
  if (delete_module(IPC_ISR_MODULE_NAME, O_NONBLOCK) != 0?) then (yes)
    :shm_err("Can't unload %s module", IPC_ISR_MODULE_NAME);
  endif
endif
stop
@enduml
