@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
while (1?) is (yes)
  if (info->rx_cb != NULL?) then (yes)
    :read(info->uio_fd, &irq_count, sizeof(irq_count));
  endif
  repeat
    :work = info->rx_cb(info->instance, IPC_SOFTIRQ_BUDGET);
    :sched_yield();
  repeat while (work >= IPC_SOFTIRQ_BUDGET?) is (yes)
  :ipcsHwIrqEnable(info->instance);
endwhile (no)
stop
@enduml
