@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
if (rx_cb == NULL?) then (yes)
  :return -EINVAL;
  stop
endif
if ((instance invalid)?) then (yes)
  :return -EINVAL;
  stop
endif
:request_mem_region(local); ioremap(local_virt_shm);
if (local map failed?) then (yes)
  :release local region; return -ENOMEM;
  stop
endif
:request_mem_region(remote); ioremap(remote_virt_shm);
if (remote map failed?) then (yes)
  :iounmap local; release local; return -ENOMEM;
  stop
endif
:save shm_size, phys addrs; priv.rx_cb = rx_cb;
if (inter_core_rx_irq == IPC_IRQ_NONE?) then (yes)
  :irq_num = IPC_IRQ_NONE;
else (no)
  :of_find_compatible_node MSCM; of_irq_get;
  if (mscm missing?) then (yes)
    :iounmap remote/local; release regions; return -ENXIO;
    stop
  endif
endif
while (i < IPC_SHM_MAX_INSTANCES?) is (yes)
  if (irq_num == irq_num_init[i]?) then (yes)
    :state = ENABLED; return 0;
    stop
  endif
  :i++;
endwhile (no)
:irq_num_init[instance] = irq_num;
if (irq_num != IPC_IRQ_NONE?) then (yes)
  :request_irq(ipcsShmHardirq);
  if (request_irq failed?) then (yes)
    :iounmap remote/local; release regions; return err;
    stop
  endif
endif
:state = ENABLED; return 0;
stop
@enduml
