@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
:priv.id[instance].state = IPC_SHM_INSTANCE_DISABLED;
:ipcsHwIrqDisable(instance);
:tasklet_kill(&ipc_shm_rx_tasklet);
if (irq_num_init[instance] != 0?) then (yes)
  :free_irq(priv.id[instance].irq_num, &priv);
  :irq_num_init[instance] = 0;
endif
:iounmap remote; release_mem_region remote;
:iounmap local; release_mem_region local;
stop
@enduml
