@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
:sprintf(uio_name, "instance_%u", instance);
:nentries = scandir(IPC_SHM_UIO_DIR);
if (nentries < 0?) then (yes)
  :return -EIO;
stop
endif
while (count > 0?) is (yes)
  :err_name = line_match(name_path, uio_name)\nerr_version = line_match(version_path, DRIVER_VERSION);
  if (matched?) then (yes)
    :strcpy(dev_name, name_list[count]->d_name);
    break
    endif
  :count--;
endwhile (no)
:free name_list entries;
if (found?) then (yes)
  :return 0;
else (no)
  :return -ENONET;
endif
stop
@enduml
