@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
:copy_from_user IPCS_UIO_CDEV_DATA_TYPE;
if (copy failed?) then (yes)
  :return -EFAULT; stop
else (no)
endif
if (instance >= IPC_SHM_MAX_INSTANCES?) then (yes)
  :return -EINVAL; stop
else (no)
endif
:store data; ipcsUioInit(&data);
if (err?) then (yes)
  :return err; stop
else (no)
endif
:return sizeof(data);
stop
@enduml
