@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
if (rx_cb == NULL?) then (yes)
  :return -EINVAL;
stop
endif
:priv.id[instance].shm_size = cfg->shm_size; priv.id[instance].rx_cb = rx_cb;
if (priv.ipc_files_opened == IPC_STATUS_CLEAR?) then (yes)
  :ipc_usr_module_fd = open(IPC_USR_MODULE_PATH, O_RDONLY)\nfinit_module(ipc_usr_module_fd, "", 0);
  if ((ipc_usr_module_fd == -1) || (finit_module != 0)?) then (yes)
    :return -ENODEV;
stop
  endif
  :priv.dev_mem_fd = open(IPC_USR_DEV_MEM_NAME, O_RDWR)\npriv.ipc_usr_fd = open(IPC_USR_CDEV_NAME, O_RDWR);
  if ((dev_mem_fd == -1) || (ipc_usr_fd == -1)?) then (yes)
    :close(priv.dev_mem_fd)\nclose(priv.ipc_usr_fd)\nclose(ipc_usr_module_fd)\nreturn -ENODEV;
stop
  endif
  :priv.ipc_files_opened = IPC_STATUS_SET;
endif
:page_phys_addr = (cfg->local_shm_addr / page_size) * page_size\nlocal_shm_offset = cfg->local_shm_addr - page_phys_addr\nlocal_shm_map = mmap(NULL, local_shm_offset + cfg->shm_size, PROT_READ | PROT_WRITE, MAP_SHARED, dev_mem_fd, page_phys_addr)\nlocal_virt_shm = local_shm_map + local_shm_offset;
if (local_shm_map == MAP_FAILED?) then (yes)
  :return -ENOMEM;
stop
endif
:page_phys_addr = (cfg->remote_shm_addr / page_size) * page_size\nremote_shm_offset = cfg->remote_shm_addr - page_phys_addr\nremote_shm_map = mmap(NULL, remote_shm_offset + cfg->shm_size, PROT_READ | PROT_WRITE, MAP_SHARED, dev_mem_fd, page_phys_addr)\nremote_virt_shm = remote_shm_map + remote_shm_offset;
if (remote_shm_map == MAP_FAILED?) then (yes)
  :munmap(local_shm_map); return -ENOMEM;
stop
endif
if (priv.ipc_soft_created == IPC_STATUS_CLEAR?) then (yes)
  :pthread_attr_init(&irq_thread_attr)\npthread_attr_setschedpolicy(&irq_thread_attr, RX_SOFTIRQ_POLICY)\npthread_attr_setschedparam(&irq_thread_attr, &irq_thread_param)\nerr = pthread_create(&priv.irq_thread_id, &irq_thread_attr, ipcsShmSoftirq, &priv);
  if (err == -1?) then (yes)
    :munmap(remote_shm_map, remote_shm_offset + shm_size)\nmunmap(local_shm_map, local_shm_offset + shm_size)\nreturn err;
stop
  endif
  :priv.ipc_soft_created = IPC_STATUS_SET;
endif
:err = ioctl(priv.ipc_usr_fd, IPC_CDEV_CMD_SET_INSTANCE, instance);
if (!err) err = ioctl(priv.ipc_usr_fd, IPC_CDEV_CMD_INIT_INSTANCE, cfg);
if (err?) then (yes)
  :munmap(remote_shm_map, remote_shm_offset + shm_size)\nmunmap(local_shm_map, local_shm_offset + shm_size)\nreturn err;
stop
endif
if (cfg->inter_core_rx_irq == IPC_IRQ_NONE?) then (yes)
  :priv.id[instance].irq_num = IPC_IRQ_NONE;
else (no)
  :priv.id[instance].irq_num = 0;
endif
:priv.id[instance].state = IPC_SHM_INSTANCE_ENABLED; return 0;
stop
@enduml
