@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
:node = of_find_compatible_node(DT_INTC_NODE_COMP);
if (node == NULL?) then (yes)
  :return NULL;
stop
endif
:err = of_address_to_resource(node, 0, &res)\nof_node_put(node);
if (err?) then (yes)
  :return NULL;
stop
endif
:return ioremap(res.start, resource_size(&res));
stop
@enduml
