@startuml
!pragma layout smetana
skinparam conditionStyle insideDiamond
skinparam linetype ortho
start
while (forever?) is (yes)
  if (rx_cb != NULL?) then (yes)
    :read(uio_fd, irq_count) block until kernel IRQ;
  else (no)
  endif
  repeat
    :work = rx_cb(instance, budget);
    if (work >= budget?) then (yes)
      :sched_yield();
    else (no)
    endif
  repeat while (work >= budget?) is (yes)
  :ipcsHwIrqEnable(instance);
endwhile (no)
stop
@enduml
